# Appearance
appearance:
  mode: system
  color: blue


# Site header
header:
  navbar:
    enable: true
    show_search: true
    show_theme_chooser: true



# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
