theme: jekyll-theme-architect
title: Aria's Website!
description: Dear Earth, thanks for visiting!


# --- Background colour/image options --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour


page-col: "#ccffff"


# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

# navbar-img: "/img/bgimage.png"
# footer-img: "/img/bgimage.png"
# page-img: "/img/bgimage.png"



#Aria 아영 さくら φ
#off when busy,ttyl.G calendar scheduling: ariafyy@gmail.com
