theme: jekyll-theme-architect
title: Aria's Website!
description: Dear Earth, thanks for visiting.


# --- Background colour/image options --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#ccffff"
page-col: "#FFFFFF"


# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

# navbar-img: "/img/bgimage.png"
# footer-img: "/img/bgimage.png"
# page-img: "/img/bgimage.png"



#Aria 아영 さくら φ
#off when busy,ttyl.G calendar scheduling: ariafyy@gmail.com

# Sidebar settings
sidebar: true                           
sidebar-about-description: "안녕하세용 こんにちは Hola"
#sidebar-avatar: /img/avatar-Jack.jpg     #你的大头贴，请使用绝对地址.

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate


date_format: "%B %-d, %Y"
read_time: true
